### ISSUE TITLE
这个Repo使用哪种许可证? 

### ISSUE THREAD

**Issue by charlieJ107** [kirainmoe/xmu-course-upload-helper-chrome-extension#1]
这个仓库使用了何种许可证? 或者如何获取授权? 是否允许通过修改和再分发来适配其他浏览器?

**Comment by kirainmoe** [comment]
> 这个仓库使用了何种许可证? 或者如何获取授权?

MIT

> 是否允许通过修改和再分发来适配其他浏览器?

允许，欢迎移植到其它浏览器。

**Comment by charlieJ107** [comment]
已经移植并发布至Firefox浏览器，插件已经获得Firefox签名，可以直接前往
https://github.com/charlieJ107/xmu-course-upload-helper-extension
下载使用
Release版本已发布在https://github.com/charlieJ107/xmu-course-upload-helper-extension/releases/tag/v1.0.3
